version: '3.5'
services:
  train:
    image: sr-train
    build:
      shm_size: '8gb'
      context: .
    volumes:
      - .:/src
      - /mnt/scratch/ssense/images_dump:/src/data/fashiongen
    entrypoint: [python, train.py]

  api:
    image: sr-api
    build:
      shm_size: '8gb'
      context: .
      dockerfile: Dockerfile
    environment:
      MODEL_PATH: ${MODEL_PATH}
    volumes:
      - /mnt/home/thomas/models_t_shirts/:/models
      - .:/src
    ports:
      - "5001:5001"
